name: Continuos Intergratopn and Deployment

#this action should be run when something is pushed to the main branch
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: check out code
        uses: actions/checkout@v2

      - name: Setup .NET 3
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "3.1.x"

      - name: Restore dependencies
        run: dotnet restore
        working-directory: ./Livestream Backend application

      - name: Build app
        run: dotnet build -c Release --no-restore
        working-directory: ./Livestream Backend application

      - name: Run Automated test
        run: dotnet test -c Release --no-build
        working-directory: ./Livestream Backend application
        
     #  - name: Publish app
       #  run: dotnet publish -c -o ./out
        # working-directory: ./Livestream Backend application
        
      
#       - name: Deploy to Azure 
 #        uses: azure/login@v1
  #       with:
   #        creds: ${{ secrets.AZURE_CREDENTIALS }}

#       - uses: azure/sql-action@v1
  #       with:
        
    #       server-name: SQL_SERVER_NAME
      #     connection-string: ${{ secrets.AZURE_SQL_CONNECTION_STRING }}
        #   dacpac-package: './Database.dacpac'

      # Azure logout 
      # - name: logout
       #  run: |
        #   az logout
